server:
  port: 8085
spring:
  application:
    name: eurekaClient2
eureka:
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/
active: wohahahnininininini5555555516661111
